<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8c6d4132-183a-4464-a062-2793edfa31cf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CatalogApi\ElBruno.AspireMonitor.SampleHarness.CatalogApi.csproj" />
    <ProjectReference Include="..\OrdersApi\ElBruno.AspireMonitor.SampleHarness.OrdersApi.csproj" />
    <ProjectReference Include="..\Worker\ElBruno.AspireMonitor.SampleHarness.Worker.csproj" />
  </ItemGroup>

</Project>
